version: '3.5'
services:
  user-service:
    image: ghcr.io/news-aggregator-bot/bepicky.user-service
    environment:
      - MYSQL_USERSERVICE_DB=${MYSQL_USERSERVICE_DB}
      - MYSQL_USERSERVICE_USER=${MYSQL_USERSERVICE_USER}
      - MYSQL_USERSERVICE_PASSWORD=${MYSQL_USERSERVICE_PASSWORD}
      - SPRING_PROFILES_ACTIVE=${SPRING_PROFILES_ACTIVE}
    healthcheck:
      test: [ "CMD", "curl", "-f", "http://localhost:9050/actuator/health" ]
      interval: 60s
      timeout: 5s
      retries: 3
    ports:
      - 9050:9050
    deploy:
      resources:
        limits:
          cpus: "0.5"
          memory: "300M"
        reservations:
          cpus: "0.1"
          memory: "128M"
networks:
  default:
    external:
      name: picky
